on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: Test coverage

jobs:
  test-coverage-ubuntu:
    name: "Linux"
    if: "! contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ubuntu-16.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: n1hility/cancel-previous-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          workflow: Test-coverage.yml
        if: "!startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/master'"
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master

      - uses: r-lib/actions/setup-pandoc@master

      - name: Install Ubuntu dependencies
        run: sudo apt-get install libcurl4-openssl-dev
      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ubuntu-r-4.0-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ubuntu-r-4.0-1-

      - name: Install dependencies
        run: |
          install.packages(c("posterior", "cmdstanr", "remotes"),repos = c("https://mc-stan.org/r-packages/", getOption("repos")))
          cmdstanr::install_cmdstan(cores = 2, overwrite = TRUE, release_url = "https://github.com/stan-dev/cmdstan/releases/download/v2.24.1/cmdstan-2.24.1.tar.gz")
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran("covr")
          remotes::install_cran("gridExtra")
        shell: Rscript {0}

      - name: Test coverage
        run: covr::codecov(type = "all")
        shell: Rscript {0}

  test-coverage-windows:
    name: "Windows"
    if: "! contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: windows-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Download RTools 
        run: Invoke-WebRequest -Uri https://cran.r-project.org/bin/windows/Rtools/rtools40-x86_64.exe -OutFile ./R40.exe
        shell: powershell
      
      - name: Download RTools 
        run: Start-Process -FilePath ./R40.exe -ArgumentList /VERYSILENT -NoNewWindow -Wait
        shell: powershell
  
      - name: Set paths
        run: |
          echo "::add-path::C:/rtools40/usr/bin"
          echo "::add-path::C:/rtools40/mingw64/bin"
        shell: powershell
      
      - name: Install mingw32-make
        run: |
          pacman -Syu mingw-w64-x86_64-make --noconfirm
        shell: powershell

      - uses: r-lib/actions/setup-r@master
        with:
              r-version: 'release'

      - uses: r-lib/actions/setup-pandoc@master

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
        shell: Rscript {0}

      - name: Install dependencies
        run: |
          install.packages(c("posterior", "cmdstanr", "remotes"),repos = c("https://mc-stan.org/r-packages/", getOption("repos")))
          cmdstanr::install_cmdstan(cores = 2, overwrite = TRUE, release_url = "https://github.com/stan-dev/cmdstan/releases/download/v2.24.1/cmdstan-2.24.1.tar.gz")
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran("covr")
          remotes::install_cran("gridExtra")
        shell: Rscript {0}

      - name: Test coverage
        run: covr::codecov(type = "all")
        shell: Rscript {0}